### ISSUE TITLE
Server Error after upgrade to 2.3.5

### ISSUE THREAD

**Issue by mpatcheco** [digitalocean/netbox#2239]
### Issue type
[ ] Feature request 
[X] Bug report      
[ ] Documentation   
[ ] Housekeeping    

After an upgrade from 2.3.1 to 2.3.4, when access main functions (Sites, Tenants, Racks, etc ..) a error is showed

 **There was a problem with your request. Please contact an administrator.

The complete exception is provided below:
<class 'TypeError'>
__init__() got an unexpected keyword argument 'name'**

### Environment
* Python version:  python34-3.4.8-1
* NetBox version:  2.3.5

### Description

A lot of users are having the same issue upgrading from 2.3.4 or even on a fresh install of a 2.3.5

Discussion link:
https://groups.google.com/forum/#!topic/netbox-discuss/h35vs7dkbRQ%5B1-25%5D

**Comment by mpatcheco** [comment]
According to @jeremystretch a quick fix is to downgrade django-filter

**pip3 install django-filter==1.1.0**

**Comment by mmahacek** [comment]
Bump that I had the same error after upgrading 2.3.4 to 2.3.5.  Downgrading django-filter from 2.0.0 to 1.1.0 seems to have fixed it for me.

**Comment by snazy2000** [comment]
Same, thanks for the fix @mpatcheco

**Comment by drybjed** [comment]
This issue makes the current `master` branch of NetBox uninstallable out of the box, at least with Python 2.7 on Debian Stretch. Any plans for fixing that, or should switch to Python3 `virtualenv` solve this?

**Comment by jeremystretch** [comment]
@drybjed The issue is with the new release of the django-filter library; using a virtualenv (or not) won't make any difference.

I'm going to return to my earlier approach of pinning exact versions of all required libraries in `requirements.txt` to mitigate this issue in the future. Will push out a new release with this change today.

**Comment by drybjed** [comment]
@jeremystretch Excellent, thanks for quick reaction. :-)
