### ISSUE TITLE
Unable to export IP addresses

### ISSUE THREAD

**Issue by Mika56** [digitalocean/netbox#1582]
### Issue type
[ ] Feature request 
[x] Bug report      
[ ] Documentation   

### Environment
* Python version: 3.5.3  
* NetBox version: 2.2.1 

### Description
Hi,

After upgrading from 2.1.4 to 2.2.1, I cannot export IP addresses. I have no particular reproduction steps, clicking exports on my end display an error page with:

```
<class 'AttributeError'>

'IPAddress' object has no attribute 'virtual_machine'
```

I am available to provide any data that might help fixing this bug
